import type { Metadata } from "next";

import "@/assets/fonts";
import "@/styles";

import { Header } from "@/components";

export const metadata: Metadata = {
  title: "Денисевич Светлана",
  description: "Generated by create next app",
  icons: "/favicon.svg",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
